[2021-03-22 21:15:08,613] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-03-21T00:00:00+00:00 [queued]>
[2021-03-22 21:15:08,626] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-03-21T00:00:00+00:00 [queued]>
[2021-03-22 21:15:08,627] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 21:15:08,627] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-22 21:15:08,627] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 21:15:08,634] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_after_loop> on 2021-03-21T00:00:00+00:00
[2021-03-22 21:15:08,637] {standard_task_runner.py:52} INFO - Started process 74 to run task
[2021-03-22 21:15:08,639] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', '2021-03-21T00:00:00+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpcdol_acs', '--error-file', '/tmp/tmpk4h61_60']
[2021-03-22 21:15:08,640] {standard_task_runner.py:77} INFO - Job 12: Subtask run_after_loop
[2021-03-22 21:15:08,669] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.run_after_loop 2021-03-21T00:00:00+00:00 [running]> on host 699fbf69fb73
[2021-03-22 21:15:08,696] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2021-03-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-21T00:00:00+00:00
[2021-03-22 21:15:08,697] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-03-22 21:15:08,698] {bash.py:158} INFO - Running command: echo 1
[2021-03-22 21:15:08,703] {bash.py:169} INFO - Output:
[2021-03-22 21:15:08,703] {bash.py:173} INFO - 1
[2021-03-22 21:15:08,704] {bash.py:177} INFO - Command exited with return code 0
[2021-03-22 21:15:08,721] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20210321T000000, start_date=20210322T211508, end_date=20210322T211508
[2021-03-22 21:15:08,739] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-22 21:15:08,773] {local_task_job.py:146} INFO - Task exited with return code 0
